    price: 499,
    features: [
      'EU AI Act essentials',
      'Risk classification',
      'Compliance basics',
      'Certificate of completion',
      'Lifetime access to materials',
      '1 year certificate validity',
    ],
    targetAudience: [
      'Compliance officers',
      'Project managers',
      'Business analysts',
      'Policy makers',
    ],
    governmentIntegration: false,
    blockchainCertificate: false,
    validityPeriod: '1 year',
  },
  {
    name: 'professional',
    title: 'CEASA Professional',
    subtitle: 'Industry-recognized certification',
    duration: '12 weeks',
    modules: 20,
    questions: 200,
    price: 999,
    features: [
      'All Fundamentals content',
      'Advanced risk assessment',
      'Conformity assessment procedures',
      'Quality management systems',
      'Sector-specific compliance',
      'Government portal integration',
      'Blockchain-verified certificate',
      'Job board access',
      'Professional community',
      '2 year certificate validity',
      'Continuing education credits',
    ],
    targetAudience: [
      'AI safety analysts',
      'Compliance auditors',
      'Enterprise architects',
      'Regulatory consultants',
    ],
    prerequisites: 'CEASA Fundamentals or equivalent experience',
    governmentIntegration: true,
    blockchainCertificate: true,
    validityPeriod: '2 years',
  },
  {
    name: 'expert',
    title: 'CEASA Expert',
    subtitle: 'Regulatory-level expertise',
    duration: '16 weeks',
    modules: 30,
    questions: 300,
    price: 1999,
    features: [
      'All Professional content',
      'Advanced regulatory procedures',
      'Notified Body operations',
      'Policy development',
      'International harmonization',
      'Research projects',
      'Mentorship program',
      'Government agency access',
      'Blockchain + multi-signature certificates',
      'Speaking opportunities',